version: "3"
services:
  so-rabbit:
    image: 'rabbitmq:3.13.2-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 2s
      timeout: 2s
      retries: 30
  
  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-gateway
      - payment-service
      - payment-gateway
      - order-gateway
      - stock-service

    
  order-gateway:
    build: ./order_gateway
    image: order-gateway:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_gateway.env
    depends_on:
      so-rabbit:
        condition: service_healthy


  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: sh -c "python consumer.py"
    env_file:
      - env/order_redis.env
    depends_on:
      order-db:
        condition: service_started
      so-rabbit:
        condition: service_healthy

  order-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb


  stock-gateway:
    build: ./stock_gateway
    image: stock-gateway:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_gateway.env
    depends_on:
      so-rabbit:
        condition: service_healthy

  stock-service:
    build: ./stock
    image: stock:latest
    command: sh -c "python consumer.py"
    env_file:
      - env/stock_redis.env
    depends_on:
      stock-db:
        condition: service_started
      so-rabbit:
        condition: service_healthy

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-gateway:
    build: ./payment_gateway
    image: payment-gateway:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_gateway.env
    depends_on:
      so-rabbit:
        condition: service_healthy

  payment-service:
    build: ./payment
    image: user:latest
    command: sh -c "python consumer.py"
    env_file:
      - env/payment_redis.env
    depends_on:
      payment-db:
        condition: service_started
      so-rabbit:
        condition: service_healthy

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
