STOCK_QUEUE= "STOCK_QUEUE"
ORDER_QUEUE = "ORDER_QUEUE"
PAYMENT_QUEUE="PAYMENT_QUEUE"

STATUS_SUCCESS = 200
STATUS_CLIENT_ERROR = 400
STATUS_SERVER_ERROR = 500

DB_ERROR_STR = "DB error"
REQ_ERROR_STR = "Requests error"
SERV_ERROR_STR = "Server error"

MAX_RETRIES = 3
SLEEP_TIME = 10

LAST_UPD_LIMIT = 25